### PR TITLE
47 58 examples vignettes

### LINKED ISSUE #47: vignette for executing scripts with timber

### LINKED ISSUE #58: Example Log on Get Stated Page
Use an iframe to showcase scrollable log.

### PR DESCRIPTION
**Pull request by bms63**
Close #47 Close #58

### Thank you for your Pull Request! 

We have developed a Pull Request template to aid you and our reviewers.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the timber codebase remains robust and consistent.  

### The spirit of timber

While many packages to facilitate the logging of code already exist in the R ecosystem, it is hard to find a solution that works well for clinical programming applications. Many logging implementations are more implicit and rely on user input to create the log for the execution of a script. While this is useful for logging specific events of an application, in clinical programming a log has a set purpose.

timber is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well as the environment that it happened in. We set out to create a flexible logging utility that could provide the necessary information to anyone reviewing the code execution so they can recreate the execution environment and run the code for themselves. Please make sure your Pull Request meets this **spirit of timber**.

Please check off each taskbox as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `dev` branch until you have checked off each task.

- [x] The spirit of timber is met in your Pull Request
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests
- [x] Creation/updates to relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### gif showcasing the addin
* Can see gif on the readme for this branch
image

### Dropdown for articles with themes 
image

### Scrollable iframe for script and log file
image

Thoughts:

*  Where do we store some of this stuff for the vignettes?
*  Switch to latest pkgdown and have search ability?

### CODE REVIEW

**Comment by bms63** [comment]
Umm...3.5 and 3.6 do not like my gif

**Comment by bms63** [comment]
@kodesiba all checks are passing now after update. 

can you do a dev version of website to see if gif populates to home page?

fyi htmls for iframes are in vignettes - not sure if this is bad practice.

**Comment by bms63** [comment]
ummm...there is an issue with vignette("timber")  not rendering on the website.

**Comment by kodesiba** [comment]
> @kodesiba all checks are passing now after update.
> 
> can you do a dev version of website to see if gif populates to home page?
> 
> fyi htmls for iframes are in vignettes - not sure if this is bad practice.

Would those make more sense as articles instead of vignettes since they are static HTML files that don't really need to be included with the package but are for the pkgdown? https://usethis.r-lib.org/reference/use_vignette.html

**Comment by bms63** [comment]
> > @kodesiba all checks are passing now after update.
> > can you do a dev version of website to see if gif populates to home page?
> > fyi htmls for iframes are in vignettes - not sure if this is bad practice.
> 
> Would those make more sense as articles instead of vignettes since they are static HTML files that don't really need to be included with the package but are for the pkgdown? https://usethis.r-lib.org/reference/use_vignette.html

I'm done for whatever.  I'm just having trouble visualizing how it all goes together?  

Ben

**Comment by bms63** [comment]
Rebuilt site.  Looks great and everything is rendering.

**Pull request merged**
