### PR TITLE
Get functions used and compare to approved packages and functions

### PR DESCRIPTION
**Pull request by nicholas-masel**
#6 
#9 

- Added parsing to identify packages and functions used via `utils::getParseData()` inside of `get_used_functions()`
- Added option `timber.approved` to store the path to a tibble containing approved packages and functions.
- Added `approved.rda` to show an example of the expected data structure for the approved packages and functions.
  ``` r
  timber::approved
  #> # A tibble: 6 × 2
  #>   function_name library      
  #>   <chr>         <chr>        
  #> 1 library       package:base 
  #> 2 %>%           package:dplyr
  #> 3 group_by      package:dplyr
  #> 4 summarize     package:dplyr
  #> 5 mean          package:base 
  #> 6 pivot_wider   package:tidyr
  ```
- Added function `get_unapproved_use()` to compare used to approved to find unapproved use
- Added write functions for both used packages and unapproved
- Added testing for new functions including supporting files in `thatthat/tests/ref/` to parse
- Added more dependencies than you would probably prefer

### CODE REVIEW

**Comment by bms63** [comment]
@nicholas-masel Nathan (@kodesiba ) and I are meeting tomorrow.  Hopefully, we can get this PR finished out for you.  Also very curious how we can all start collaborating on this package and get it into the pharmaverse - as I see it being mentioned in presentations all the time.  

Thanks again for this PR and being active on this!  I'm trying to get gsk to start using it in their pipeline too!

**Comment by nicholas-masel** [comment]
@bms63 Thanks for the update!

I've reached out to Nathan and Mike to work through the steps to get added to the dev team so I can join in on future discussions.  I hope we can meet on the next chat, see what's next and how I can help.

**Comment by bms63** [comment]
> @bms63 Thanks for the update!
> 
> I've reached out to Nathan and Mike to work through the steps to get added to the dev team so I can join in on future discussions. I hope we can meet on the next chat, see what's next and how I can help.

Awesome!  I hope we get to work together.  I'm not even sure I'm supposed to be working on this package, but I really want to see it deployed to the masses!

**Review by kodesiba — APPROVED** [review]

**Comment by kodesiba** [comment]
@nicholas-masel I'm good for you to merge this to dev

**Pull request merged**
