### PR TITLE
#8 Updated log file to have File Name and File Path

### LINKED ISSUE #8: Program name missing in log file
One crucial thing I am missing in the log file is the name of the script being run, So far it seems the log only contains the name of the log file at the bottom but that does not necessarily have the same name as the script being `axecuted`.

### PR DESCRIPTION
**Pull request by bms63**
Closes #8 

I was thinking the User and File information should be in the same section.  

image

Later in the log file there is Program Run Time information.  Perhaps instead of File Name and File Path they should be Program Name and Program Path and the Section Heading should be User and Program Information

Also...getting strange warnings when running tests...I'm on RStudio Cloud so this might be a Server issue

image

### CODE REVIEW

**Comment by thomasp-b** [comment]
@bms63, I've just updated a test to reflect the updated section name. The changes look good to me.

**Review by kodesiba — APPROVED** [review]

**Comment by kodesiba** [comment]
@bms63 all of this looks good to me, perfectly fine throwing it in a common section.  Added the linked issue to your PR notes so it'll close when this is done.

Also want to tag @thomas-neitmann on this to see if he has anything to add since it was originally an issue from him.

**Review by kodesiba — APPROVED** [review]

**Review by kodesiba — APPROVED** [review]

**Comment by kodesiba** [comment]
@nicholas-masel this should be ready to review, if you have some time to check it out that would be awesome.  @bms63 take a look at these updates and make sure I didn't miss anything, I can't add you as a reviewer but tagging you here

**Comment by bms63** [comment]
This looks good to me!  I'll wait till @nicholas-masel  takes a gander before we merge.

**Comment by kodesiba** [comment]
@nicholas-masel tagging you here if you have time to look at this one as well

**Review by nicholas-masel — APPROVED** [review]

**Pull request merged**
